// @ts-nocheck
/**
 * Project Forge — GitHub delivery layer.
 *
 * Replaces the old `execSync('gh repo create ...')` (the gh CLI is installed
 * nowhere, so every push silently failed and github_created stayed false).
 *
 * Zero npm dependencies and NO `git` binary required: creates the repo and
 * pushes all files in a single commit using the GitHub REST + Git Data API
 * via the Node 20 global `fetch`.
 *
 * Config (env):
 *   GITHUB_PAT     fine-grained or classic PAT with `repo` (and `Contents`
 *                  read/write + `Administration` for repo creation) scope.
 *   GITHUB_OWNER   optional; defaults to the authenticated user's login.
 */

const API = 'https://api.github.com';

function token(): string {
  const t = process.env.GITHUB_PAT || process.env.GITHUB_TOKEN;
  if (!t) throw new Error('GitHub not configured: set GITHUB_PAT (repo scope) in .env');
  return t;
}

export function githubConfigured(): boolean {
  return Boolean(process.env.GITHUB_PAT || process.env.GITHUB_TOKEN);
}

export function githubConfigStatus(): { configured: boolean; token_source: string | null; owner: string | null; reason?: string } {
  const tokenSource = process.env.GITHUB_PAT ? 'GITHUB_PAT' : (process.env.GITHUB_TOKEN ? 'GITHUB_TOKEN' : null);
  if (!tokenSource) {
    return {
      configured: false,
      token_source: null,
      owner: process.env.GITHUB_OWNER || null,
      reason: 'Missing GITHUB_PAT or GITHUB_TOKEN in backend environment',
    };
  }
  return {
    configured: true,
    token_source: tokenSource,
    owner: process.env.GITHUB_OWNER || null,
  };
}

async function gh(path: string, init: any = {}): Promise<any> {
  const res = await fetch(path.startsWith('http') ? path : `${API}${path}`, {
    ...init,
    headers: {
      Authorization: `Bearer ${token()}`,
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
      'User-Agent': 'project-forge',
      ...(init.body ? { 'Content-Type': 'application/json' } : {}),
      ...(init.headers || {}),
    },
  });
  const text = await res.text();
  const data = text ? JSON.parse(text) : {};
  if (!res.ok) {
    const msg = data?.message || text || res.statusText;
    const err: any = new Error(`GitHub ${res.status} ${path}: ${msg}`);
    err.status = res.status;
    err.data = data;
    throw err;
  }
  return data;
}

async function authedLogin(): Promise<string> {
  if (process.env.GITHUB_OWNER) return process.env.GITHUB_OWNER;
  const me = await gh('/user');
  return me.login;
}

/** Ensure the repo exists; create it if missing. Returns {owner, repo, html_url, defaultBranch, created}. */
export async function ensureRepo(name: string, opts: { description?: string; private?: boolean } = {}): Promise<any> {
  const owner = await authedLogin();
  try {
    const existing = await gh(`/repos/${owner}/${name}`);
    return { owner, repo: name, html_url: existing.html_url, defaultBranch: existing.default_branch || 'main', created: false };
  } catch (e: any) {
    if (e.status !== 404) throw e;
  }
  const created = await gh('/user/repos', {
    method: 'POST',
    body: JSON.stringify({
      name,
      description: opts.description?.slice(0, 350) || 'Generated by Project Forge',
      private: opts.private !== false,
      auto_init: false,
    }),
  });
  return { owner, repo: name, html_url: created.html_url, defaultBranch: created.default_branch || 'main', created: true };
}

/**
 * Create the repo (if needed) and push all files as a single commit.
 * files: array of { path, content }.
 */
export async function createRepoAndPush(opts: {
  name: string;
  description?: string;
  private?: boolean;
  files: { path: string; content: string }[];
  commitMessage?: string;
}): Promise<{ html_url: string; owner: string; repo: string; created: boolean; fileCount: number }> {
  if (!opts.files?.length) throw new Error('createRepoAndPush: no files to push');
  const repoName = sanitizeRepoName(opts.name);
  const { owner, repo, html_url, defaultBranch, created } = await ensureRepo(repoName, opts);

  // 1) Create a blob for each file.
  const blobs: { path: string; sha: string }[] = [];
  for (const f of opts.files) {
    const blob = await gh(`/repos/${owner}/${repo}/git/blobs`, {
      method: 'POST',
      body: JSON.stringify({ content: Buffer.from(f.content ?? '', 'utf-8').toString('base64'), encoding: 'base64' }),
    });
    blobs.push({ path: f.path.replace(/^\/+/, ''), sha: blob.sha });
  }

  // 2) Determine parent commit (if repo already had content).
  let parentSha: string | undefined;
  let baseTree: string | undefined;
  try {
    const ref = await gh(`/repos/${owner}/${repo}/git/ref/heads/${defaultBranch}`);
    parentSha = ref.object.sha;
    const parentCommit = await gh(`/repos/${owner}/${repo}/git/commits/${parentSha}`);
    baseTree = parentCommit.tree.sha;
  } catch {
    parentSha = undefined; // empty repo, first commit
  }

  // 3) Create tree.
  const tree = await gh(`/repos/${owner}/${repo}/git/trees`, {
    method: 'POST',
    body: JSON.stringify({
      ...(baseTree ? { base_tree: baseTree } : {}),
      tree: blobs.map((b) => ({ path: b.path, mode: '100644', type: 'blob', sha: b.sha })),
    }),
  });

  // 4) Create commit.
  const commit = await gh(`/repos/${owner}/${repo}/git/commits`, {
    method: 'POST',
    body: JSON.stringify({
      message: opts.commitMessage || 'Initial commit — generated by Project Forge 🔨',
      tree: tree.sha,
      ...(parentSha ? { parents: [parentSha] } : {}),
    }),
  });

  // 5) Point the branch ref at the new commit (create or fast-forward).
  if (parentSha) {
    await gh(`/repos/${owner}/${repo}/git/refs/heads/${defaultBranch}`, {
      method: 'PATCH',
      body: JSON.stringify({ sha: commit.sha, force: true }),
    });
  } else {
    await gh(`/repos/${owner}/${repo}/git/refs`, {
      method: 'POST',
      body: JSON.stringify({ ref: `refs/heads/${defaultBranch}`, sha: commit.sha }),
    });
  }

  return { html_url, owner, repo, created, fileCount: opts.files.length };
}

export function sanitizeRepoName(title: string): string {
  return (title || 'forge-project')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 90) || 'forge-project';
}
